const nextRoutes = require('next-routes')
const {join} = require('path')
const routes = (module.exports = nextRoutes())

routes.add('index', '/')
routes.add('loginPage', '/login/:page/:param', 'login')
routes.add('login', '/login')
routes.add('fames', '/fames/:pageNumber')
routes.add('fame', '/fame/:fameId')
routes.add('400', '/:other', '404')
routes.add('404', '404')
