export default [
  {value: 'SouthAfrica', label: 'آفریقای جنوبی'},
  {value: 'Antigua-Barbuda', label: 'آنتیگوآ و باربودا'},
  {value: 'Andorra', label: 'آندورا' },
  {value: 'Azerbaijan', label: 'آذربایجان'},
  {value: 'Argentina', label: 'آرژانتین'},
  {value: 'Aruba', label: 'آروبا'},
  {value: 'CentralAfricanRepublic', label: 'آفریقای مرکزی'},
  {value: 'UnitedStates', label: 'آمریکا'},
  {value: 'Angola', label: 'آنگولا'},
  {value: 'Anguilla', label: 'آنگویلا'},
  {value: 'Albania', label: 'آلبانی' },
  {value: 'Germany', label: 'آلمان'},
  {value: 'Austria', label: 'اتریش'},
  {value: 'Ethiopia', label: 'اتیوپی'},
  {value: 'Jordan', label: 'اردن'},
  {value: 'Armenia', label: 'ارمنستان'},
  {value: 'Uruguay', label: 'اروگوئه'},
  {value: 'Eritrea', label: 'اریتره'},
  {value: 'Uzbekistan', label: 'ازبکستان'},
  {value: 'Spain', label: 'اسپانیا'},
  {value: 'Australia', label: 'استرالیا'},
  {value: 'Estonia', label: 'استونی'},
  {value: 'Slovakia', label: 'اسلواکی'},
  {value: 'Slovenia', label: 'اسلوونی'},
  {value: 'Afghanistan', label: 'افغانستان' },
  {value: 'Ecuador', label: 'اکوادور'},
  {value: 'Algeria', label: 'الجزایر' },
  {value: 'ElSalvador', label: 'ال سالوادور'},
  {value: 'UnitedArabEmirates', label: 'امارات متحده عربی'},
  {value: 'Indonesia', label: 'اندونزی'},
  {value: 'UnitedKingdom', label: 'انگلستان'},
  {value: 'Ukraine', label: 'اوکراین'},
  {value: 'Uganda', label: 'اوگاندا'},
  {value: 'Italy', label: 'ایتالیا'},
  {value: 'Iran', label: 'ایران'},
  {value: 'Ireland', label: 'ایرلند'},
  {value: 'Iceland', label: 'ایسلند'},

  {value: 'Barbados', label: 'باربادوس'},
  {value: 'Bahamas', label: 'باهاما'},
  {value: 'Bahrain', label: 'بحرین'},
  {value: 'Brazil', label: 'برزیل'},
  {value: 'Bermuda', label: 'برمودا'},
  {value: 'Burma(Myanmar)', label: 'برمه میانمار'},
  {value: 'Brunei', label: 'برونئی'},
  {value: 'Belarus', label: 'بلاروس'},
  {value: 'Belgium', label: 'بلژیک'},
  {value: 'Bulgaria', label: 'بلغارستان'},
  {value: 'Belize', label: 'بلیز'},
  {value: 'Bangladesh', label: 'بنگلادش'},
  {value: 'Benin', label: 'بنین'},
  {value: 'Bhutan', label: 'بوتان'},
  {value: 'Botswana', label: 'بوتسوانا'},
  {value: 'BurkinaFaso', label: 'بورکینافاسو'},
  {value: 'Bosnia-Herzegowina', label: 'بوسنی و هرزگوین'},
  {value: 'Bolivia', label: 'بولیوی'},
  {value: 'Burundi', label: 'بروندی'},
  {value: 'BouvetIsland', label: 'بووت'},

  {value: 'PapuaNewGuinea', label: 'پاپوا - گینه نو'},
  {value: 'Paraguay', label: 'پاراگوئه'},
  {value: 'Pakistan', label: 'پاکستان'},
  {value: 'Palau', label: 'پالو'},
  {value: 'Panama', label: 'پاناما'},
  {value: 'Portugal', label: 'پرتغال'},
  {value: 'Peru', label: 'پرو'},
  {value: 'PuertoRico', label: 'پورتوریکو'},
  {value: 'FrenchPolynesia', label: 'پولنیزی فرانسه'},
  {value: 'Pitcairn', label: 'پیتکایرن'},

  {value: 'Tajikistan', label: 'تاجیکستان'},
  {value: 'Tanzania', label: 'تانزانیا'},
  {value: 'Thailand', label: 'تایلند'},
  {value: 'Taiwan', label: 'تایوان'},
  {value: 'Turkmenistan', label: 'ترکمنستان'},
  {value: 'Turkey', label: 'ترکیه'},
  {value: 'Trinidad-Tobago', label: 'ترینیداد و توباگو'},
  {value: 'Turks-CaicosIslands', label: 'تورکس و کایکوس'},
  {value: 'Tunisia', label: 'تونس'},
  {value: 'Tokelau', label: 'توکلو'},
  {value: 'Togo', label: 'توگو'},
  {value: 'Tonga', label: 'تونگا'},
  {value: 'Tuvalu', label: 'تووالیو'},
  {value: 'EastTimor', label: 'تیمور شرقی'},

  {value: 'Jamaica', label: 'جامائیکا'},
  {value: 'Gibraltar', label: 'جبل الطارق'},
  {value: 'SolomonIslands', label: 'جزایر سلیمان'},
  {value: 'ChristmasIsland', label: 'جزیره کریسمس'},
  {value: 'MarshallIslands', label: 'جزایر مارشال'},
  {value: 'NorfolkIsland', label: 'جزیره نورفک'},
  {value: 'Georgia', label: 'جورجیا'},
  {value: 'Djibouti', label: 'جی بوتی'},

  {value: 'Chad', label: 'چاد'},
  {value: 'Czech', label: 'چک'},
  {value: 'China', label: 'چین'},

  {value: 'Denmark', label: 'دانمارک'},
  {value: 'Dominica', label: 'دومینیکا'},
  {value: 'Dominican', label: 'دومینیکن'},

  {value: 'Reunion', label: 'راونیون'},
  {value: 'Rwanda', label: 'رواندا'},
  {value: 'Russia', label: 'روسیه'},
  {value: 'Romania', label: 'رومانی'},

  {value: 'Zambia', label: 'زامبیا'},
  {value: 'Zimbabwe', label: 'زیمباوه'},

  {value: 'Japan', label: 'ژاپن'},

  {value: 'SaoTome-Principe', label: 'سائوتوم و پرینسیپ'},
  {value: 'IvoryCoast', label: 'ساحل عاج'},
  {value: 'Samoa', label: 'ساموآ'},
  {value: 'SanMarino', label: 'سان ماریو'},
  {value: 'SriLanka', label: 'سریلانکا'},
  {value: 'SaintKitts-Nevis', label: 'سنت کیتس و نویس'},
  {value: 'SaintLucia', label: 'سنت لوسیا'},
  {value: 'St.Helena', label: 'سنت هلنا'},
  {value: 'SaintVincent-Grenadines', label: 'سنت ونسانت و گرنادین'},
  {value: 'Singapore', label: 'سنگاپور'},
  {value: 'Senegal', label: 'سنگال'},
  {value: 'Somalia', label: 'سومالی'},
  {value: 'SierraLeona', label: 'سیرالئون'},
  {value: 'Seychelles', label: 'سیشل'},
  {value: 'St.Pierre-Miquelon', label: 'سنت پیرو میکلون'},
  {value: 'Sweden', label: 'سوئد'},
  {value: 'Switzerland', label: 'سوئیس'},
  {value: 'Sudan', label: 'سودان'},
  {value: 'Suriname', label: 'سورینام'},
  {value: 'Swaziland', label: 'سوازیلند'},
  {value: 'Svalbard-JanMayen', label: 'سوالبارد و یان ماین'},
  {value: 'Syria', label: 'سوریه'},

  {value: 'Chile', label: 'شیلی'},

  {value: 'WesternSahara', label: 'صحرای عربی'},

  {value: 'Iraq', label: 'عراق'},
  {value: 'SaudiArabia', label: 'عربستان صعودی'},
  {value: 'Oman', label: 'عمان'},

  {value: 'Ghana', label: 'غنا'},

  {value: 'Faroe', label: 'فارو'},
  {value: 'Falkland', label: 'فالکند'},
  {value: 'France', label: 'فرانسه'},
  {value: 'France-Metro', label: 'فرانسه مترو'},
  {value: 'Finland', label: 'فنلاند'},
  {value: 'Fiji', label: 'فیجی'},
  {value: 'Philippines', label: 'فیلیپین'},

  {value: 'Cyprus', label: 'قبرس'},
  {value: 'Kyrgyzstan', label: 'قرقیزستان'},
  {value: 'Kazakhstan', label: 'قزاقستان'},
  {value: 'Antarctica', label: 'قطب جنوب'},
  {value: 'Qatar', label: 'قطر'},

  {value: 'CostaRica', label: 'کاستاریکا'},
  {value: 'NewCaledonia', label: 'کالدونیای جدید'},
  {value: 'Cambodia', label: 'کامبوج'},
  {value: 'Cameroon', label: 'کامرون'},
  {value: 'Canada', label: 'کانادا'},
  {value: 'Croatia', label: 'کرواسی'},
  {value: 'SouthKorea', label: 'کره جنوبی'},
  {value: 'NorthKorea', label: 'کره شمالی'},
  {value: 'Colombia', label: 'کلمبیا'},
  {value: 'Congo', label: 'کنگو'},
  {value: 'Kenya', label: 'کنیا'},
  {value: 'Cuba', label: 'کوبا'},
  {value: 'CookIslands', label: 'کوک'},
  {value: 'CocosIsles', label: 'کوکو'},
  {value: 'Comoros', label: 'کوموروس'},
  {value: 'Kuwait', label: 'کویت'},
  {value: 'CapeVerde', label: 'کیپورد'},
  {value: 'Kiribati', label: 'کیری باتی'},

  {value: 'Gabon', label: 'گابن'},
  {value: 'Gambia', label: 'گامبیا'},
  {value: 'Grenada', label: 'گرنادا'},
  {value: 'Greenland', label: 'گرین لند'},
  {value: 'Guatemala', label: 'گواتمالا'},
  {value: 'Guadeloupe', label: 'گوادالوپ'},
  {value: 'Guam', label: 'گوام'},
  {value: 'FrenchGuiana', label: 'گویان فرانسه'},
  {value: 'Guyana', label: 'گیانا'},
  {value: 'Guinea', label: 'گینه'},
  {value: 'EquatorialGuinea', label: 'گینه استوایی'},
  {value: 'Guinea-Bissau', label: 'گینه بیسائو'},

  {value: 'Laos', label: 'لائوس'},
  {value: 'Lebanon', label: 'لبنان'},
  {value: 'Latvia', label: 'لتونی'},
  {value: 'Lesotho', label: 'لسوتو'},
  {value: 'Luxembourg', label: 'لوکزامبورگ'},
  {value: 'Poland', label: 'لهستان'},
  {value: 'Liberia', label: 'لیبریا'},
  {value: 'Libya', label: 'لیبی'},
  {value: 'Lithuania', label: 'لیتوانی'},
  {value: 'Liechtenstein', label: 'لیختن اشتاین'},

  {value: 'Madagascar', label: 'ماداگاسکار'},
  {value: 'Martinique', label: 'مارتینیک'},
  {value: 'Mayotte', label: 'مایوت'},
  {value: 'Macau', label: 'ماکائو'},
  {value: 'Malawi', label: 'مالاوی'},
  {value: 'Malta', label: 'مالت'},
  {value: 'Maldives', label: 'مالدیو'},
  {value: 'Malaysia', label: 'مالزی'},
  {value: 'Mali', label: 'مالی'},
  {value: 'Hungary', label: 'مجارستان'},
  {value: 'Morocco', label: 'مراکش'},
  {value: 'Egypt', label: 'مصر'},
  {value: 'Mongolia', label: 'مغولستان'},
  {value: 'Macedonia', label: 'مقدونیه'},
  {value: 'Mexico', label: 'مکزیک'},
  {value: 'Mauritania', label: 'موریتانیا'},
  {value: 'Mauritius', label: 'موری تیوس'},
  {value: 'Mozambique', label: 'موزامبیک'},
  {value: 'Moldova', label: 'مولداوی'},
  {value: 'Monaco', label: 'موناکو'},
  {value: 'Montserrat', label: 'مونتسررات'},

  {value: 'Namibia', label: 'نامیبیا'},
  {value: 'Nepal', label: 'نپال'},
  {value: 'Norway', label: 'نروژ'},
  {value: 'Nauru', label: 'نائورو'},
  {value: 'Niger', label: 'نیجر'},
  {value: 'Nigeria', label: 'نیجریه'},
  {value: 'Nicaragua', label: 'نیکاراگوئه'},
  {value: 'NewZealand', label: 'نیوزیلند'},
  {value: 'Niue', label: 'نیووی'},

  {value: 'Vatican', label: 'واتیکان'},
  {value: 'Wallis-Futuna', label: 'والیس و فوتونا'},
  {value: 'Vanuatu', label: 'وانواتو'},
  {value: 'Venezuela', label: 'ونزوئلا'},
  {value: 'Vietnam', label: 'ویتنام'},

  {value: 'Haiti', label: 'هائیتی'},
  {value: 'Netherlands', label: 'هلند'},
  {value: 'India', label: 'هند'},
  {value: 'Honduras', label: 'هندوراس'},
  {value: 'HongKong', label: 'هونگ کونگ'},

  {value: 'Yemen', label: 'یمن'},
  {value: 'Yugoslavia', label: 'یوگوسلاوی'},
  {value: 'Greece', label: 'یونان'},
]
